// Package video's only Go artifact is this sync gate: the committed
// walkthrough GIFs are renders of the tape scripts in this directory, and
// nothing else ties the two together. record.sh fingerprints every input
// that shapes the videos into videos.lock at render time; this test fails
// the ordinary `go test ./...` the moment those inputs drift — the signal
// that the GIFs no longer show the product as it is.
//
// Out of sync? Re-record: bash e2e/video/record.sh
package video

import (
	"crypto/sha256"
	"encoding/hex"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
)

// lockLine matches sha256sum output lines in videos.lock: "<64 hex>  <path>".
var lockLine = regexp.MustCompile(`^([0-9a-f]{64})\s+(\S+)$`)

func TestVideosInSyncWithSources(t *testing.T) {
	lock, err := os.ReadFile("videos.lock")
	if err != nil {
		t.Fatalf("reading videos.lock (generated by record.sh at render time): %v", err)
	}

	checked := 0
	for _, line := range strings.Split(string(lock), "\n") {
		m := lockLine.FindStringSubmatch(strings.TrimSpace(line))
		if m == nil {
			continue // comments / metadata lines
		}
		want, path := m[1], m[2]
		data, err := os.ReadFile(path)
		if err != nil {
			t.Errorf("videos.lock lists %s but it is unreadable: %v", path, err)
			continue
		}
		sum := sha256.Sum256(data)
		if got := hex.EncodeToString(sum[:]); got != want {
			t.Errorf("%s changed since the walkthrough videos were last recorded — the committed GIFs no longer match it. Re-record: bash e2e/video/record.sh", path)
		}
		checked++
	}
	if checked == 0 {
		t.Fatal("videos.lock contains no fingerprint lines — re-record: bash e2e/video/record.sh")
	}

	// Every video source that shapes the render must be fingerprinted —
	// a new tape or gate that isn't in the lock would otherwise drift silently.
	for _, glob := range []string{"parts/*.tape", "gate-*.sh"} {
		names, err := filepath.Glob(glob)
		if err != nil {
			t.Fatalf("globbing %s: %v", glob, err)
		}
		for _, name := range names {
			if !strings.Contains(string(lock), name) {
				t.Errorf("%s is not fingerprinted in videos.lock — re-record: bash e2e/video/record.sh", name)
			}
		}
	}

	// Every GIF promised by videos.yaml must actually exist in docs/assets.
	meta, err := os.ReadFile("videos.yaml")
	if err != nil {
		t.Fatalf("reading videos.yaml: %v", err)
	}
	gifRe := regexp.MustCompile(`(?m)^\s*-\s*gif:\s*(\S+)`)
	for _, m := range gifRe.FindAllStringSubmatch(string(meta), -1) {
		if _, err := os.Stat("../../" + m[1]); err != nil {
			t.Errorf("videos.yaml promises %s but it does not exist: %v", m[1], err)
		}
	}
}
